CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    MEMBER_PW VARCHAR2(20) NOT NULL,
    MEMBER_NAME VARCHAR2(20) NOT NULL,
    MEMBER_PHONE VARCHAR2(13) NOT NULL,
    MEMBER_EMAIL VARCHAR2(30) NOT NULL,
    MEMBER_ADDRESS VARCHAR2(50) NOT NULL,
    MEMBER_ENROLLDATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    MEMBER_ADMIN NUMBER NOT NULL
);
CREATE TABLE PRODUCT(
     PRODUCT_ID NUMBER PRIMARY KEY,
     PRODUCT_NAME VARCHAR2(20) NOT NULL UNIQUE,
     PRODUCT_PRICE NUMBER NOT NULL,
     PRODUCT_COUNT NUMBER NOT NULL,
     PRODUCT_DESCRPIT VARCHAR2(100) NOT NULL
);
CREATE TABLE CART(
    CART_TBL NUMBER PRIMARY KEY,
    PROUDCT_ID NUMBER REFERENCES PRODUCT(PRODUCT_ID),
    PRODUCT_COUNT NUMBER NOT NULL
);
CREATE TABLE PAYMENT(
    PAYMENT_ID NUMBER PRIMARY KEY,
    PAYMENT_NUMBERS NUMBER NOT NULL,
    PAYMENT_TOTALPRICE NUMBER NOT NULL,
    USER_ID VARCHAR2(20) REFERENCES MEMBER(MEMBER_ID),
    PRODUCT_ID NUMBER REFERENCES PRODUCT(PRODUCT_ID)
);
CREATE SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_PRODUCT;
CREATE SEQUENCE SEQ_CART;
CREATE SEQUENCE SEQ_PAYMENT;

DROP TABLE PAYMENT_TBL;
DROP TABLE CART_TBL;
DROP TABLE PRODUCT_TBL;
DROP TABLE PRODUCT;