CREATE TABLE USER_TBL(
    USER_ID VARCHAR2(20) PRIMARY KEY,
    USER_PW VARCHAR2(20) NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL,
    USER_PHONE VARCHAR2(13) NOT NULL,
    USER_EMAIL VARCHAR2(30) NOT NULL,
    USER_ADDRESS VARCHAR2(50) NOT NULL,
    USER_ENROLLDATE TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE TABLE PRODUCT_TBL(
     PRODUCT_ID NUMBER PRIMARY KEY,
     PRODUCT_NAME VARCHAR2(20) NOT NULL UNIQUE,
     PRODUCT_PRICE NUMBER NOT NULL,
     PRODUCT_COUNT NUMBER NOT NULL,
     PRODUCT_DESCRPIT VARCHAR2(100) NOT NULL
);
CREATE TABLE CART_TBL(
    CART_TBL NUMBER PRIMARY KEY,
    PROUDCT_ID NUMBER REFERENCES PRODUCT_TBL(PRODUCT_ID),
    PRODUCT_COUNT NUMBER NOT NULL
);
CREATE TABLE PAYMENT_TBL(
    PAYMENT_ID NUMBER PRIMARY KEY,
    PAYMENT_NUMBERS NUMBER NOT NULL,
    PAYMENT_TOTALPRICE NUMBER NOT NULL,
    USER_ID VARCHAR2(20) REFERENCES USER_TBL(USER_ID),
    PRODUCT_ID NUMBER REFERENCES PRODUCT_TBL(PRODUCT_ID)
);
CREATE SEQUENCE SEQ_USER_TBL;
CREATE SEQUENCE SEQ_PRODUCT_TBL;
CREATE SEQUENCE SEQ_CART_TBL;
CREATE SEQUENCE SEQ_PAYMENT_TBL;
